[tool.poetry]
name = "notebooks"
version = "0.1.0"
description = ""
authors = ["Mateus Almeida <mateusalmeida881@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.3.0"
numpy = "^2.3.0"
mlforecast = "^1.0.2"
seaborn = "^0.13.2"
matplotlib = "^3.10.3"
scipy = "^1.15.3"
statsmodels = "^0.14.4"
ipykernel = "^6.29.0"
pyarrow = "^20.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
